# Generated by Django 5.0.6 on 2024-08-10 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browseproduct', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cards',
            name='image',
            field=models.FileField(null=True, upload_to='cards/'),
        ),
    ]
