# Generated by Django 5.0.6 on 2024-09-02 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browseproduct', '0002_cards_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='cards',
            name='category',
            field=models.CharField(default=1, max_length=60),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cards',
            name='image',
            field=models.FileField(null=True, upload_to='browseproduct/'),
        ),
    ]
